# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69c9a23f218086a454610bcc0d82834a"
name = "ai-product-app"
handle = "ai-product-app-1"
application_url = "https://muscle-frontpage-icon-prot.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sitepluse.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://muscle-frontpage-icon-prot.trycloudflare.com/auth/callback",
  "https://muscle-frontpage-icon-prot.trycloudflare.com/auth/shopify/callback",
  "https://muscle-frontpage-icon-prot.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
